In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3])

In [4]:
a.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [5]:
type(a)

numpy.ndarray

In [6]:
np.shape(a)

(3,)

In [7]:
a[1]

2

In [8]:
#matriz

In [9]:
b = np.array([[1,2,3],
             [4,5,6],
             [7,8,9]
             ])

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.shape(b)

(3, 3)

In [14]:
c = np.zeros ((2,3))
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
d = np.ones ((4,2))
d

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
f = np.full ((5,2), 7)
f

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [18]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
g = b[1:, 1:]
g

array([[5, 6],
       [8, 9]])

In [23]:
g2 = b [0:2, 0:2]
g2

array([[1, 2],
       [4, 5]])

In [24]:
g

array([[5, 6],
       [8, 9]])

In [29]:
g[1,1] = 2021

In [30]:
g

array([[   5,    6],
       [   8, 2021]])

In [31]:
b

array([[   1,    2,    3],
       [   4,    5,    6],
       [   7,    8, 2021]])

In [32]:
b[1,1]=50500

In [33]:
g

array([[50500,     6],
       [    8,  2021]])

In [35]:
x=np.array([
    [1,2],
    [3,4]
],
dtype=np.float64)

y = np.array([
    [5,6],
    [7,8]    
],
dtype = np.float64)
print (x)
print (y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [36]:
print('sum of matrix \n{} y \n{} is :\n{} '.format(x,y,x+y))

sum of matrix 
[[1. 2.]
 [3. 4.]] y 
[[5. 6.]
 [7. 8.]] is :
[[ 6.  8.]
 [10. 12.]] 


In [39]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


comp = x+y == np.add(x,y)
comp

In [40]:
comp = x+y == np.add(x,y) 
comp

array([[ True,  True],
       [ True,  True]])

In [41]:
print(np.array_equal(x+y, np.add(x,y)))

True


In [43]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]
